services:
  app:
    container_name: deep_research
    build: .
    volumes:
      - ./:/app/
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "8878:8878"
    command: sh -c "npm install && sh"
